//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aphro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModelContainer : DbContext
    {
        public DataModelContainer()
            : base("name=DataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<event_types> event_types { get; set; }
        public DbSet<locations> locations { get; set; }
        public DbSet<seats> seats { get; set; }
        public DbSet<events> events { get; set; }
        public DbSet<event_seating> event_seating { get; set; }
        public DbSet<group_requests> group_requests { get; set; }
        public DbSet<people> people { get; set; }
        public DbSet<seasons> seasons { get; set; }
        public DbSet<guests> guests { get; set; }
    }
}
