//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aphro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_seating
    {
        public int seat_id { get; set; }
        public int event_id { get; set; }
        public int person_id { get; set; }
        public string reserved_type { get; set; }
    
        public virtual people person { get; set; }
        public virtual seats seat { get; set; }
        public virtual events @event { get; set; }
    }
}
