//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aphro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_types
    {
        public event_types()
        {
            this.events = new HashSet<events>();
        }
    
        public int event_type_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<events> events { get; set; }
    }
}
