//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aphro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class locations
    {
        public locations()
        {
            this.events = new HashSet<events>();
            this.seats = new HashSet<seats>();
        }
    
        public int location_id { get; set; }
        public string name { get; set; }
        public int total_seats { get; set; }
    
        public virtual ICollection<events> events { get; set; }
        public virtual ICollection<seats> seats { get; set; }
    }
}
