//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aphro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class people
    {
        public people()
        {
            this.event_seating = new HashSet<event_seating>();
            this.group_requests = new HashSet<group_requests>();
            this.group_requests1 = new HashSet<group_requests>();
        }
    
        public int person_id { get; set; }
        public string student_id { get; set; }
        public string teacher_id { get; set; }
        public int guest_id { get; set; }
        public int season_id { get; set; }
    
        public virtual ICollection<event_seating> event_seating { get; set; }
        public virtual ICollection<group_requests> group_requests { get; set; }
        public virtual ICollection<group_requests> group_requests1 { get; set; }
        public virtual seasons season { get; set; }
        public virtual guests guest { get; set; }
    }
}
