//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aphro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seasons
    {
        public seasons()
        {
            this.events = new HashSet<events>();
            this.people = new HashSet<people>();
        }
    
        public int season_id { get; set; }
        public string name { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual ICollection<events> events { get; set; }
        public virtual ICollection<people> people { get; set; }
    }
}
