//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aphro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seats
    {
        public seats()
        {
            this.event_seating = new HashSet<event_seating>();
        }
    
        public int seat_id { get; set; }
        public int location_id { get; set; }
        public bool is_balcony { get; set; }
        public bool is_prime { get; set; }
        public string seat_row { get; set; }
        public string seat_section { get; set; }
        public int seat_number { get; set; }
    
        public virtual locations location { get; set; }
        public virtual ICollection<event_seating> event_seating { get; set; }
    }
}
